Motor Details
SaneMyburg/motorbike-front-end pull request #6
Opened 2023-09-28 18:18 UTC by AliShahSafdari

- Add the Motorbike details

2023-09-28 19:42 UTC, mohametalmeari approved these changes
Hi @AliShahSafdari 
Great job creating the details page. This part of the project is complete and there is nothing else to say other than... it is time to merge. 
Congrats! 🏅🎉

2023-09-28 20:36 UTC, WilhelmK109 commented on src/components/Details.js
> +    </div>
- You did well by implementing the `Go to Home` link. One of the requirements is that "In the details page, the user can click the "Reserve" button. Please kindly fix this.

2023-09-28 20:46 UTC, WilhelmK109 requested changes
Hi @AliShahSafdari,
Great job implementing most of the requirements for the Details page task. There are some issues that need improvement for you to move to the next task, but you are almost there.

![AlmostThereReachGIF](https://github.com/SaneMyburg/motorbike-front-end/assets/74548443/eeeb21fa-f436-4cb0-af0d-d4a4c884948a)

Please see the comments below:

2023-09-29 06:13 UTC, SaneMyburg approved these changes
## STATUS: APPROVED 🟢
Hi @AliShahSafdari ,

Your project is complete! There is nothing else to say other than... it's time to merge it :
Congratulations! 🎉

#### (Highlights) Good Points: 👍
- You documented your work professionally. ✔
- You used GitHub flow correctly. ✔
- Awesome job! Creating details page✔🥳 🥳
- This milestone's requirements have been met with success. 🎉 🎉 🎉 ✔
#### Optional suggestions
Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

2023-09-29 06:13 UTC, merged